# Generated by Django 5.0.3 on 2024-05-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("publish_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Genre", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
