# Generated by Django 5.0.3 on 2024-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_game_studio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="publish_date",
            field=models.DateField(null=True),
        ),
    ]
