# Generated by Django 5.0.4 on 2024-05-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_game_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='publish_date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='Genre',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
