# Generated by Django 5.0.4 on 2024-05-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_publish_date_game_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='studio',
        ),
    ]
