# Generated by Django 5.0.4 on 2024-05-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_game_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
