# Generated by Django 5.0.3 on 2024-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_game_description_remove_game_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(default="Default Game Name", max_length=20),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
